kind: Deployment
apiVersion: apps/v1
metadata:
  name: cpu-stress
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: polinux/stress
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "1100m"
        command: ["stress"]
        args: ["--cpu", "1", "--vm-hang", "1"]