kind: Deployment
apiVersion: apps/v1
metadata:
  name: memory-stress
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: polinux/stress-ng
        resources:
          requests:
            memory: "128Mi"
            cpu: "5m"
          limits:
            memory: "1152Mi"
            cpu: "100m"
        args: ["--vm", "1", "--vm-bytes", "1024M", "--vm-keep"]