kind: ResourceQuota
apiVersion: v1
metadata:
  name: test
  namespace: test
spec:
  hard:
    limits.cpu: 5000m
    limits.memory: 5.5Gi
    pods: '100'
    requests.cpu: 1000m
    requests.memory: 1Gi

