kind: Deployment
apiVersion: apps/v1
metadata:
  name: memory-stress
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: polinux/stress
        resources:
          requests:
            memory: "1024Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "1024M", "--vm-hang", "1"]