apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  annotations:
    mco-observatorium-image: 'blue0/observatorium:fork'
    mco-observatorium_operator-image: 'blue0/observatorium-operator:vfix'
  name: observability
spec:
  advanced:
    observatoriumAPI:
      additionalWriteEndpoint: 'http://vector:9090'
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 30
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 10Gi

