apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  annotations:
    mco-observatorium-image: 'quay.io/llan/observatorium:vfix'
    mco-observatorium_operator-image: 'quay.io/llan/observatorium-operator:vfix'
  name: observability
spec:
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 60
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    writeStorage:
    - key: ep.yaml
      name: victoriametrics
    - key: ep.yaml
      name: vector
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 10Gi

