kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-observability
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'monitoring.coreos.com'
    resources:
      - prometheusrules

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-observability
subjects:
  - kind: ServiceAccount
    name: multicluster-observability-operator
    namespace: open-cluster-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-observability
