kind: Deployment
apiVersion: apps/v1
metadata:
  name: victoriametrics
  namespace: open-cluster-management-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      securityContext:
        fsGroup: 1000700000
      containers:
        - name: victoriametrics
          image: >-
            victoriametrics/victoria-metrics
          ports:
            - name: http
              containerPort: 8428
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /victoria-metrics-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: victoriametrics

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: victoriametrics
  namespace: open-cluster-management-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
  volumeMode: Filesystem

---
kind: Service
apiVersion: v1
metadata:
  name: victoriametrics
  namespace: open-cluster-management-observability
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8428
      targetPort: http
  type: ClusterIP
  selector:
    app: victoriametrics